#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Installing dependencies"
npm install

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ deploy@212.71.245.46:/var/www/212.71.245.46/
echo "Deployment complete"
